id = "019b6263-3ec3-70c1-b3f7-f126286e8c02"
description = "ðŸ›«adsf"
paid_by_entity = "3abaaf40-a35a-488d-8ef2-0184c8c5f3c3"
currency_iso_4217 = "CHF"
amount = 1337.42
transaction_datetime_rfc_3339 = 2024-11-17 14:43:02Z

[[split_ratios]]
entity_id = "c8744a29-7ed0-447a-af5a-51e4ad291d1d"
ratio = "1/2"

[[split_ratios]]
entity_id = "92c0a0fc-aa86-4922-ab1f-7b9326720177"
ratio = "1/2"
