description = "ðŸ›«"
paid_by_entity = 2
currency_iso_4217 = "CHF"
amount = 598.80
transaction_datetime_rfc_3339 = "2025-11-17T14:43Z"

[[split_ratios]]
entity_id = 1
ratio = "1/3"

[[split_ratios]]
entity_id = 2
ratio = "1/3"

[[split_ratios]]
entity_id = 3
ratio = "1/3"
