id = "019b5b3b-25e7-7e53-a0b6-0af3afde297c"
description = "ğŸ«ğŸ–ğŸ°"
paid_by_entity = "3abaaf40-a35a-488d-8ef2-0184c8c5f3c3"
currency_iso_4217 = "CHF"
amount = 220.0
transaction_datetime_rfc_3339 = 2025-11-17 14:42:55Z

[[split_ratios]]
entity_id = "c8744a29-7ed0-447a-af5a-51e4ad291d1d"
ratio = "1/3"

[[split_ratios]]
entity_id = "3abaaf40-a35a-488d-8ef2-0184c8c5f3c3"
ratio = "1/3"

[[split_ratios]]
entity_id = "92c0a0fc-aa86-4922-ab1f-7b9326720177"
ratio = "1/3"
